# Generated by Django 3.0.3 on 2020-03-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200317_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='insertdate_completed',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
