# Generated by Django 3.0.3 on 2020-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200317_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='insertdate_completed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
